In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import pickle

In [4]:
data_preprocessed = pd.read_csv('df_preprocessed.csv')
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [5]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day  \
0         0         0         0         1            7    1   
1         0         0         0         0            7    1   
2         0         0         0         1            7    2   
3         1         0         0         0            7    3   
4         0         0         0         1            7    3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [6]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [7]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

In [8]:
data_preprocessed['Excessive Absenteeism'] = targets

In [9]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day  \
0         0         0         0         1            7    1   
1         0         0         0         0            7    1   
2         0         0         0         1            7    2   
3         1         0         0         0            7    3   
4         0         0         0         1            7    3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [10]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [11]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day  \
0         0         0         0         1            7    1   
1         0         0         0         0            7    1   
2         0         0         0         1            7    2   
3         1         0         0         0            7    3   
4         0         0         0         1            7    3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [13]:
data_with_targets.shape

(700, 15)

In [14]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day  \
0           0         0         0         1            7    1   
1           0         0         0         0            7    1   
2           0         0         0         1            7    2   
3           1         0         0         0            7    3   
4           0         0         0         1            7    3   
5           0         0         0         1            7    4   
6           0         0         1         0            7    4   
7           0         0         0         1            7    4   
8           0         0         1         0            7    0   
9           0         0         1         0            7    0   
10          1         0         0         0            7    0   
11          1         0         0         0            7    1   
12          1         0         0         0            7    2   
13          1         0         0         0            7    2   
14          0         0         0         1            7    2   
15          1         0         0         0            7    4   
16          0         0         0         1            7    4   
17          0         0         1         0            7    0   
18          1         0         0         0            7    3   
19          0         0         0         1            8    2   
20          1         0         0         0            8    2   
21          1         0         0         0            8    0   
22          1         0         0         0            8    0   
23          0         0         0         1            8    4   
24          0         0         1         0            8    0   
25          0         0         0         1            8    0   
26          0         0         0         1            8    1   
27          0         0         0         1            8    2   
28          0         0         1         0            8    2   
29          0         0         0         1            8    4   
30          0         0         1         0            8    0   
31          0         0         1         0            8    3   
32          0         0         0         1            8    3   
33          0         0         1         0            8    0   
34          0         0         0         1            8    0   
35          0         0         0         1            8    0   
36          0         0         0         1            8    1   
37          1         0         0         0            8    3   
38          0         0         0         1            8    4   
39          0         0         0         1            8    4   
40          0         0         0         1            9    1   
41          0         0         0         1            9    0   
42          0         0         0         1            9    1   
43          0         0         1         0            9    1   
44          0         0         0         1            9    2   
45          0         0         0         1            9    6   
46          0         0         0         1            9    0   
47          0         0         0         1            9    3   
48          0         0         1         0            9    4   
49          1         0         0         0            9    0   
50          0         0         0         0            9    0   
51          0         0         0         0            9    0   
52          0         0         0         1            9    1   
53          0         0         0         1            9    1   
54          0         0         0         0            9    1   
55          0         0         0         0            9    1   
56          0         0         1         0            9    2   
57          0         0         0         1            9    2   
58          0         0         0         0            9    2   
59          0         0         0         1            9    4   
60          0         0         0       

In [15]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month_Value',
       'Day', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [17]:
unscaled_iputs_without_dummy = unscaled_inputs[['Month_Value',
       'Day', 'Transportation Expense', 'Distance to Work','Age',
       'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets']]

In [18]:
unscaled_inputs = unscaled_inputs.drop(['Month_Value',
       'Day', 'Transportation Expense', 'Distance to Work','Age',
       'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets'], axis=1)

In [19]:
absenteeism_scaler = StandardScaler()

In [20]:
absenteeism_scaler.fit(unscaled_iputs_without_dummy)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [21]:
scaled_inputs_without_dummy = absenteeism_scaler.transform(unscaled_iputs_without_dummy)

In [22]:
scaled_inputs_without_dummy = pd.DataFrame(columns=['Month_Value',
       'Day', 'Transportation Expense', 'Distance to Work','Age',
       'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets'], data = scaled_inputs_without_dummy)

In [23]:
scaled_inputs = pd.concat([unscaled_inputs,scaled_inputs_without_dummy], axis=1)

In [24]:
scaled_inputs = scaled_inputs[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month_Value',
       'Day', 'Transportation Expense', 'Distance to Work','Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets']]

In [25]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value       Day  \
0           0         0         0         1     0.182726 -0.683704   
1           0         0         0         0     0.182726 -0.683704   
2           0         0         0         1     0.182726 -0.007725   
3           1         0         0         0     0.182726  0.668253   
4           0         0         0         1     0.182726  0.668253   
5           0         0         0         1     0.182726  1.344231   
6           0         0         1         0     0.182726  1.344231   
7           0         0         0         1     0.182726  1.344231   
8           0         0         1         0     0.182726 -1.359682   
9           0         0         1         0     0.182726 -1.359682   
10          1         0         0         0     0.182726 -1.359682   
11          1         0         0         0     0.182726 -0.683704   
12          1         0         0         0     0.182726 -0.007725   
13          1         0         0         0     0.182726 -0.007725   
14          0         0         0         1     0.182726 -0.007725   
15          1         0         0         0     0.182726  1.344231   
16          0         0         0         1     0.182726  1.344231   
17          0         0         1         0     0.182726 -1.359682   
18          1         0         0         0     0.182726  0.668253   
19          0         0         0         1     0.468236 -0.007725   
20          1         0         0         0     0.468236 -0.007725   
21          1         0         0         0     0.468236 -1.359682   
22          1         0         0         0     0.468236 -1.359682   
23          0         0         0         1     0.468236  1.344231   
24          0         0         1         0     0.468236 -1.359682   
25          0         0         0         1     0.468236 -1.359682   
26          0         0         0         1     0.468236 -0.683704   
27          0         0         0         1     0.468236 -0.007725   
28          0         0         1         0     0.468236 -0.007725   
29          0         0         0         1     0.468236  1.344231   
30          0         0         1         0     0.468236 -1.359682   
31          0         0         1         0     0.468236  0.668253   
32          0         0         0         1     0.468236  0.668253   
33          0         0         1         0     0.468236 -1.359682   
34          0         0         0         1     0.468236 -1.359682   
35          0         0         0         1     0.468236 -1.359682   
36          0         0         0         1     0.468236 -0.683704   
37          1         0         0         0     0.468236  0.668253   
38          0         0         0         1     0.468236  1.344231   
39          0         0         0         1     0.468236  1.344231   
40          0         0         0         1     0.753746 -0.683704   
41          0         0         0         1     0.753746 -1.359682   
42          0         0         0         1     0.753746 -0.683704   
43          0         0         1         0     0.753746 -0.683704   
44          0         0         0         1     0.753746 -0.007725   
45          0         0         0         1     0.753746  2.696187   
46          0         0         0         1     0.753746 -1.359682   
47          0         0         0         1     0.753746  0.668253   
48          0         0         1         0     0.753746  1.344231   
49          1         0         0         0     0.753746 -1.359682   
50          0         0         0         0     0.753746 -1.359682   
51          0         0         0         0     0.753746 -1.359682   
52          0         0         0         1     0.753746 -0.683704   
53          0         0         0         1     0.753746 -0.683704   
54          0         0         0         0     0.753746 -0.683704   
55          0         0         0         0     0.753746 -0.683704   
56          0  

In [26]:
scaled_inputs.shape

(700, 14)

In [27]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets, train_size = 0.8, random_state = 20)

In [28]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 14) (560,)
(140, 14) (140,)


In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
reg.score(x_train,y_train)

0.7982142857142858

In [32]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
np.sum(model_outputs == y_train)/model_outputs.shape[0]

0.7982142857142858

In [34]:
reg.intercept_

array([-1.58586855])

In [35]:
reg.coef_

array([[ 2.73828768,  0.93253671,  3.39124232,  0.58935717,  0.21615413,
        -0.07184056,  0.55489307, -0.00903914, -0.15630211, -0.01756899,
         0.24545234, -0.3747649 ,  0.31913466, -0.43095187]])

In [36]:
feature_name = scaled_inputs.columns.values

In [37]:
summary_table = pd.DataFrame(columns=['Feature_Name'], data = feature_name)

In [38]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [39]:
summary_table

Feature_Name  Coefficient
0                  Reason_1     2.738288
1                  Reason_2     0.932537
2                  Reason_3     3.391242
3                  Reason_4     0.589357
4               Month_Value     0.216154
5                       Day    -0.071841
6    Transportation Expense     0.554893
7          Distance to Work    -0.009039
8                       Age    -0.156302
9   Daily Work Load Average    -0.017569
10          Body Mass Index     0.245452
11                Education    -0.374765
12                 Children     0.319135
13                     Pets    -0.430952

In [40]:
summary_table.index +=1

In [41]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

In [42]:
summary_table.sort_index()

Feature_Name  Coefficient
0                 Intercept    -1.585869
1                  Reason_1     2.738288
2                  Reason_2     0.932537
3                  Reason_3     3.391242
4                  Reason_4     0.589357
5               Month_Value     0.216154
6                       Day    -0.071841
7    Transportation Expense     0.554893
8          Distance to Work    -0.009039
9                       Age    -0.156302
10  Daily Work Load Average    -0.017569
11          Body Mass Index     0.245452
12                Education    -0.374765
13                 Children     0.319135
14                     Pets    -0.430952

In [43]:
summary_table['Odds_Ratio'] = np.exp(summary_table.Coefficient)

In [44]:
summary_table

Feature_Name  Coefficient  Odds_Ratio
1                  Reason_1     2.738288   15.460489
2                  Reason_2     0.932537    2.540947
3                  Reason_3     3.391242   29.702830
4                  Reason_4     0.589357    1.802829
5               Month_Value     0.216154    1.241294
6                       Day    -0.071841    0.930679
7    Transportation Expense     0.554893    1.741755
8          Distance to Work    -0.009039    0.991002
9                       Age    -0.156302    0.855301
10  Daily Work Load Average    -0.017569    0.982584
11          Body Mass Index     0.245452    1.278199
12                Education    -0.374765    0.687451
13                 Children     0.319135    1.375937
14                     Pets    -0.430952    0.649890
0                 Intercept    -1.585869    0.204770

In [45]:
summary_table.sort_values('Odds_Ratio', ascending=False)

Feature_Name  Coefficient  Odds_Ratio
3                  Reason_3     3.391242   29.702830
1                  Reason_1     2.738288   15.460489
2                  Reason_2     0.932537    2.540947
4                  Reason_4     0.589357    1.802829
7    Transportation Expense     0.554893    1.741755
13                 Children     0.319135    1.375937
11          Body Mass Index     0.245452    1.278199
5               Month_Value     0.216154    1.241294
8          Distance to Work    -0.009039    0.991002
10  Daily Work Load Average    -0.017569    0.982584
6                       Day    -0.071841    0.930679
9                       Age    -0.156302    0.855301
12                Education    -0.374765    0.687451
14                     Pets    -0.430952    0.649890
0                 Intercept    -1.585869    0.204770

In [46]:
reg.score(x_test,y_test)

0.7714285714285715

In [47]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.73361481, 0.26638519],
       [0.66279883, 0.33720117],
       [0.44252351, 0.55747649],
       [0.81553797, 0.18446203],
       [0.07511479, 0.92488521],
       [0.29801321, 0.70198679],
       [0.34111472, 0.65888528],
       [0.10920224, 0.89079776],
       [0.85938578, 0.14061422],
       [0.75951965, 0.24048035],
       [0.10343977, 0.89656023],
       [0.02058581, 0.97941419],
       [0.06031071, 0.93968929],
       [0.19077902, 0.80922098],
       [0.23995205, 0.76004795],
       [0.6507594 , 0.3492406 ],
       [0.71992404, 0.28007596],
       [0.15244173, 0.84755827],
       [0.3927871 , 0.6072129 ],
       [0.03702562, 0.96297438],
       [0.75832279, 0.24167721],
       [0.8081202 , 0.1918798 ],
       [0.33427697, 0.66572303],
       [0.35622688, 0.64377312],
       [0.23072885, 0.76927115],
       [0.82228704, 0.17771296],
       [0.54572455, 0.45427545],
       [0.87970087, 0.12029913],
       [0.12624977, 0.87375023],
       [0.80047712, 0.19952288],
       [0.

In [48]:
probability_excessive_absenteeism = predicted_proba[:,1]
probability_excessive_absenteeism

array([0.26638519, 0.33720117, 0.55747649, 0.18446203, 0.92488521,
       0.70198679, 0.65888528, 0.89079776, 0.14061422, 0.24048035,
       0.89656023, 0.97941419, 0.93968929, 0.80922098, 0.76004795,
       0.3492406 , 0.28007596, 0.84755827, 0.6072129 , 0.96297438,
       0.24167721, 0.1918798 , 0.66572303, 0.64377312, 0.76927115,
       0.17771296, 0.45427545, 0.12029913, 0.87375023, 0.19952288,
       0.88092398, 0.6327564 , 0.7032473 , 0.90720985, 0.1918798 ,
       0.91819341, 0.1507151 , 0.80978614, 0.35369832, 0.54177019,
       0.20224176, 0.42346486, 0.15690178, 0.40395037, 0.78881252,
       0.69359877, 0.71269032, 0.27267455, 0.18928995, 0.16111483,
       0.61819751, 0.34216715, 0.68027456, 0.27963197, 0.84429757,
       0.41250043, 0.86474027, 0.22731989, 0.34705235, 0.35296253,
       0.70882795, 0.67437197, 0.30175064, 0.8268475 , 0.13861274,
       0.26357609, 0.11081235, 0.16128214, 0.80913199, 0.84474107,
       0.14857211, 0.29937419, 0.91787603, 0.37793582, 0.53875

In [49]:
with open('model','wb') as file:
    pickle.dump(reg,file)